#!/usr/bin/python
import h5py
import sys
from glob import glob
from math import factorial
from numpy import genfromtxt, sum, array,sqrt,zeros,exp, pi,arange, sin, cos,vstack,log, mean, ones
from pylab import show, text, scatter,legend, colorbar, xlabel, ylabel, title, imshow,plot, subplot, axvspan,xlim,ylim,stem,setp
from matplotlib import gridspec
from scipy.optimize import curve_fit

# Interval of bins (a,b)
a = 190
b = 221
c = 210

# Gaussian curve equation function
def gaussian_curve(x, a, p, w):
    # a = amplitude
    # p = peak position
    # w = width

    #return a*exp(-((x-p)**2)/(2*w**2)         # Regular gaussian
    return a*exp(-(4*log(2)*(x-p)**2)/(w**2))  # In terms of FWTM

def chi2_test(observed,expected):
    chi2 = 0
    for i in range(len(observed)):
        chi2 += ((observed[i]-expected[i])**2)/expected[i]
        print ((observed[i]-expected[i])**2)/expected[i], (chi2)
    return chi2


#
def poisson_distribution(ocurrences,rate):
    return (rate**ocurrences)/(factorial(ocurrences)*exp(rate))




# Returns a list with the fit values
def gaussian_fit(y, t1, t2, t3, x1, x2,fullRange=1):
    initValues = [t1,t2,t3]

    fitValues = curve_fit(gaussian_curve,range(x1,x2),y,p0 = initValues)
    amp = fitValues[0][0]
    pkPos = fitValues[0][1]
    width = fitValues[0][2]
    fit = []
    if fullRange:
        for i in range(a,b):
            fit.append(gaussian_curve(i,amp,pkPos,width))
    else:
        for i in range(x1,x2):
            fit.append(gaussian_curve(i,amp,pkPos,width))
    fitData = [fit,amp,pkPos,width]
    return fitData


# Plot bin histogram
def plot_bin(bns):
    imshow(vstack(bns), origin='0', aspect="auto",cmap="plasma")
    axvspan(0,a, alpha=0.30, facecolor="black")
    axvspan(b,len(bns[1][0])-1, alpha=0.3, facecolor="black")
    colorbar()


# Plot the angular response
def plot_angular_response(az, el, cps):


    angle = arange(0, 2 * pi, 0.01)
    for i in range(0,36,5):
        plot(i * cos(angle), i * sin(angle), "--k", alpha=0.25, zorder=1)

    scatter(az, el, c=cps, zorder=2,cmap="plasma")
    # title("SXM Angular Response (bins " + str(a) + " to " + str(b) + ")")
    xlabel("Azimuth (deg)")
    ylabel("Elevation (deg)")
    xlim(-40,40)
    ylim(-40,40)
    #colorbar().set_label("Events/sec")


# Plot 2 gaussian fits for the data
def fit_events_rms(events):

    s = zeros(len(events[0][0]),float)
    for i in range(len(events)):
        # Sum squares
        s += (events[i][0])**2
    m = s / len(events)
    rms = sqrt(m)

    plot(range(a,b), rms,"--o",label="RMS",zorder=1)

    amp1 = max(rms)
    pkPos1 = a+list(rms).index(max(rms))
    width1 = 10

    amp2 = max(rms[int(pkPos1)-a+10:])
    pkPos2 = pkPos1+10
    width2 = 10

    rmsFit1 = gaussian_fit(rms[:(c-a)],amp1,pkPos1,width1,a,c)[0]
    rmsFit2 = gaussian_fit(rms[(c-a):],amp2,pkPos2,width2,c,b)[0]

    #chi2Fit1 = chisquare(rms[:(c-a)],rmsFit1[:(c-a)])[0]
    #chi2Fit2 = chisquare(rms[(c-a):],rmsFit2[(c-a):])[0]

    chi2Fit1 = chi2_test(rms[:(c-a)],rmsFit1[:(c-a)])
    chi2Fit2 = chi2_test(rms[(c-a):],rmsFit2[(c-a):])
    print chi2Fit1, chi2Fit2

    plot(range(a, b), rmsFit1, "--", label=r"Fit 1 ($\chi^2$ = " +str(round(chi2Fit1,2)) + ")")
    plot(range(a, b), rmsFit2, "--", label=r"Fit 2 ($\chi^2$= " + str(round(chi2Fit2,2)) + ")")

    plot(range(a,b),array(rmsFit1)+array(rmsFit2), "--", label="Sum")
    legend(loc="upper right")
   # xlabel("Bin Number")
    ylabel("Events")


# Plot counts vs bins for each individual bin array
def plot_events_all(events):

    eventsByTime = []
    temp = []
    addedFiles = []
    # Sort data from shortest time to longest
    for i in events:
        temp.append(i[1])
    while len(temp) != 0:
        for j in events:
            if j[1] == min(temp) and (j[2] not in addedFiles):
                eventsByTime.append(j)
                addedFiles.append(j[2])
                temp.remove(min(temp))
                break
    n=0
    for i in eventsByTime:
        subplot(5,8,n+1)

        amp = max(i[0])
        pkPos = a + list(i[0]).index(max(i[0]))
        width = 10
        fit = gaussian_fit(i[0], amp, pkPos, width, a, b)[0]

        plot(range(a,b),i[0], label = str(i[1])+" sec")
        plot(range(a, b), fit, "--", label="Fit")
        title(str(n+1))
        legend(loc="upper right")
        n+=1
    show()


# Plot counts vs bins for the RMS of several bin arrays
def fit_sections_rms(events):
    n=0
    m=0
    for i in range(0,len(events), 6):
        subplot(3, 3, n + 1)
        eventSection = events[i:i+6]
        fit_events_rms(eventSection)
        m+=len(eventSection)
        title(str(i+1)+" to "+str(m))
        n+=1
    show()

def rms_fit_and_residual_fit(events,mode=0):
    if mode == 1:
        n = 0
        m = 0
        outerGrid = gridspec.GridSpec(2,4)
        for i in range(0, len(events), 6):
            innerGrid = gridspec.GridSpecFromSubplotSpec(2,1,subplot_spec=outerGrid[n])

            eventSection = events[i:i + 6]
            sp1 = subplot(innerGrid[0])
            m += len(eventSection)
            title(str(i+1)+" to "+str(m))
            fit_events_rms(eventSection)
            sp2 = subplot(innerGrid[1])
            plot_residual_fit(eventSection)
            setp(sp1.get_xticklabels(), visible=False)
            n += 1
        show()
    elif mode== 0:
        sp1 = subplot(211)
        title("All Events RMS")
        fit_events_rms(events)
        subplot(212,sharex=sp1)
        plot_residual_fit(events)
        setp(sp1.get_xticklabels(), visible=False)
        show()
    elif mode == 2:
        sp1 = subplot(426)
        title("All Events RMS")
        fit_events_rms(events)
        subplot(428, sharex=sp1)
        plot_residual_fit(events)
        setp(sp1.get_xticklabels(), visible=False)
        show()


def plot_residual_fit(events):
    s = zeros(len(events[0][0]), float)
    for i in range(len(events)):
        # Sum squares
        s += (events[i][0]) ** 2
    m = s / len(events)
    rms = sqrt(m)

    plot(range(a, b), rms, "--o", label="RMS")

    amp1 = max(rms)
    pkPos1 = a + list(rms).index(max(rms))
    width1 = 10

    amp2 = max(rms[int(pkPos1) - a + 10:])
    pkPos2 = pkPos1 + 10
    width2 = 10

    rmsFit1 = gaussian_fit(rms[:(c - a)], amp1, pkPos1, width1, a, c,0)[0]
    rmsFit2 = gaussian_fit(rms[(c - a):], amp2, pkPos2, width2, c, b,0)[0]

    totalFit = rmsFit1+rmsFit2
    chi2 = chi2_test(rms, totalFit)
    plot(range(a,b),totalFit,"--r",label=r"Fit ($\chi^2$ = "+str(round(chi2,2))+")")


    residual = array(rms) - array(totalFit)
    stem(range(a,b),residual,"--c","oc", label="Residual (Avg = "+str(round(mean(residual),2))+")")
    xlabel("Bin Number")
    ylabel("Events")
    legend(loc="upper right")





# Get directories from user
#h5FilesDir = str(sys.argv[1])
#logfilesTablePath = str(sys.argv[2])

h5FilesDir = "/home/cnieves/PycharmProjects/CfA/flight_spare_data/h5_files"
logfilesTablePath = "/home/cnieves/PycharmProjects/CfA/flight_spare_data/data_table.txt"

tableData = genfromtxt(logfilesTablePath, str)   # Data from angular response measurements

# Gets all the .h5 files from the specified directory
if h5FilesDir.endswith("/"):
    filePaths = glob(h5FilesDir + "*.h5")
else:
    h5FilesDir += "/"
    filePaths = glob(h5FilesDir + "*.h5")

countsPerSec = []     # Contains cps for each bin
elevation = []        # Values for elevation (deg)
azimuth = []          # Values for azimuth (deg)
binList = []          # Contains the arrays for each individual 'bin'
eventsTimeList = []   # [All counts, total time, name of the file] to be sorted by time
counts = []           # All counts on each 'bin' array
counts1 = []

for i in filePaths:
    fileName = i[len(h5FilesDir):(len(i) - len(".h5"))]

    # Find files in the directory that match with the files on the table
    for m in tableData:
        if m[2] == fileName:  # m[2] is the logfile name on table

            # Calculate counts per second
            dataFile = h5py.File(i)
            binList.append(dataFile['data/tlm_sxm_data/hdr']['bin'])
            bins = dataFile['data/tlm_sxm_data/hdr']['bin'][:, a:b]
            dataFile.close()

            s = sum(bins, 1)
            totalTime = float(32 * len(s) / 2 + 18 * len(s) / 2)
            totalCounts = sum(bins)
            totalCounts1 = sum(bins[:35,:])
            cps = totalCounts / totalTime

            azimuth.append(float(m[0]))
            elevation.append(float(m[1]))
            countsPerSec.append(cps)
            eventsTimeList.append([sum(bins,0), totalTime, fileName])
            counts.append(totalCounts)
            counts1.append(totalCounts1)


#subplot(211),plot_bin(binList),subplot(223, aspect=1), plot_angular_response(azimuth, elevation, countsPerSec),subplot(224),fit_events_rms(eventsTimeList), show()
#plot_events_all(eventsTimeList)
#fit_sections_rms(eventsTimeList)
#rms_fit_and_residual_fit(eventsTimeList,1)

#subplot(211),plot_bin(binList),subplot(223, aspect=1), plot_angular_response(azimuth, elevation, counts), rms_fit_and_residual_fit(eventsTimeList,2)

plot_angular_response(azimuth,elevation,countsPerSec)
title("Angular Response (Events/sec)")
colorbar().set_label("Events/sec")
show()
plot_angular_response(azimuth,elevation,counts)
title("Angular Response (All Events)")
colorbar().set_label("Events")
show()
plot_angular_response(azimuth,elevation,counts1)
title("Angular Response (All Events in 14.5 min)")
colorbar().set_label("Events")
show()